### ISSUE TITLE
patch does not apply on NFD-0.7.0

### ISSUE THREAD

**Issue by yoursunny** [pollere/NDNpatches#1]
Latest release of NFD is `NFD-0.7.0`. Earlier versions are no longer usable because it is using an obsolete packet format that is no longer supported on NDN testbed.

The NFD patches provided in this repository does not apply to `NFD-0.7.0` tag.

```shell
$ git apply < ../NDNpatches/no-nacks-on-multicast-faces.patch
error: patch failed: daemon/fw/multicast-strategy.cpp:91
error: daemon/fw/multicast-strategy.cpp: patch does not apply

$ git apply < ../NDNpatches/ship-pending-interests-on-register.patch
error: patch failed: daemon/table/fib-entry.cpp:48
error: daemon/table/fib-entry.cpp: patch does not apply
error: patch failed: daemon/table/fib-entry.hpp:98
error: daemon/table/fib-entry.hpp: patch does not apply
```

To solve this problem, update the patches to match latest NFD source code.

**Comment by kmnichols** [comment]
These patches enable DNMP to work on a broadcast media and fix an on-going implementation issue in how NFD handles arriving Interests. Arriving Interests need to be placed in the PIT, which is stated correctly in section 1.2 of https://named-data.net/wp-content/uploads/2016/10/ndn-0021-7-nfd-developer-guide.pdf, but not implemented. A new registration also needs to result in a search of the PIT. NACKS on a broadcast channel should not remove pending Interests. Pollere is not currently working on DNMP so isn't planning to track the new releases of NFD which may do further violence to a broadcast model. There is a version of DNMP that is being made to work with more stable libraries which will be released when those libraries are released.
